LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := Viper4AndroidFX
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_SRC_FILES := Viper4AndroidFX/Viper4AndroidFX.apk
LOCAL_OVERRIDES_PACKAGES := AudioFX
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)
